version: '3'
services:
  users-service:
    build: ../users-service
    command: bundle exec ruby service.rb
    volumes:
      - ../users-service/:/app
    links:
      - db
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/users*"
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      RACK_ENV:
    stdin_open: true
    tty: true
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://localhost:12201'
        tag: 'users-service'

  house-service:
    build: ../house-service
    command: bundle exec ruby service.rb
    volumes:
      - ../house-service/:/app
    links:
      - db
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/houses*"
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      RACK_ENV:
    stdin_open: true
    tty: true
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://localhost:12201'
        tag: 'houses-service'

  lb:
    image: dockercloud/haproxy
    links:
      - users-service
      - house-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:

  logstash:
    build: docker/logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "12201:12201/udp"

  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Enetwork.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    # volumes:
    #   - /usr/share/elasticsearch/data

  kibana:
    build: docker/kibana/
    ports:
      - "5601:5601"