version: '3'
services:
  users-service:
    build: ../users-service
    command: bundle exec ruby service.rb
    volumes:
      - ../users-service/:/app
    links:
      - db
    ports:
      - 80
    environment:
      VIRTUAL_HOST: "*/users*"
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      RACK_ENV:
    stdin_open: true
    tty: true

  lb:
    image: dockercloud/haproxy
    links:
      - users-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: